name: Testing the library

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: execute lib tests
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          PCLOUD_USERNAME: ${{ secrets.PCLOUD_USERNAME }}
          PCLOUD_PASSWORD: ${{ secrets.PCLOUD_PASSWORD }}
